[parameters.defines.param_placehold] # snake_case_name
# int/float/bool supported
type = 'int'
rtpc = true
default_value = 50
min_value = 0
max_value = 100

# Fields below are optional
description = 'This is a description for this parameter'
# Name displayed in Wwise UI, default to auto generate title from snake_case_name. e.g. en_US => en US, this_is_title => This is Title
display_name = 'Parameter Placeholder'
# Only effective when type is 'int', options will mapped to 0, 1, 2, ...
enumeration = ["opt1", "opt2"]
# Refer to: https://www.audiokinetic.com/zh/library/edge/?source=SDK&id=plugin_xml_properties.html
user_interface = { Fine = 0.01 }
